import { Suit, Rank, Card, Hand } from '../src/poker.ts';


export const TWO_OF_HEARTS = new Card(Rank.TWO, Suit.HEARTS);
export const THREE_OF_HEARTS = new Card(Rank.THREE, Suit.HEARTS);
export const FOUR_OF_HEARTS = new Card(Rank.FOUR, Suit.HEARTS);
export const FIVE_OF_HEARTS = new Card(Rank.FIVE, Suit.HEARTS);
export const SIX_OF_HEARTS = new Card(Rank.SIX, Suit.HEARTS);
export const SEVEN_OF_HEARTS = new Card(Rank.SEVEN, Suit.HEARTS);
export const EIGHT_OF_HEARTS = new Card(Rank.EIGHT, Suit.HEARTS);
export const NINE_OF_HEARTS = new Card(Rank.NINE, Suit.HEARTS);
export const TEN_OF_HEARTS = new Card(Rank.TEN, Suit.HEARTS);
export const JACK_OF_HEARTS = new Card(Rank.JACK, Suit.HEARTS);
export const QUEEN_OF_HEARTS = new Card(Rank.QUEEN, Suit.HEARTS);
export const KING_OF_HEARTS = new Card(Rank.KING, Suit.HEARTS);
export const ACE_OF_HEARTS = new Card(Rank.ACE, Suit.HEARTS);

export const TWO_OF_SPADES = new Card(Rank.TWO, Suit.SPADES);
export const THREE_OF_SPADES = new Card(Rank.THREE, Suit.SPADES);
export const FOUR_OF_SPADES = new Card(Rank.FOUR, Suit.SPADES);
export const ACE_OF_SPADES = new Card(Rank.ACE, Suit.SPADES);

export const TWO_OF_DIAMONDS = new Card(Rank.TWO, Suit.DIAMONDS);
export const EIGHT_OF_DIAMONDS = new Card(Rank.EIGHT, Suit.DIAMONDS);
export const ACE_OF_DIAMONDS = new Card(Rank.ACE, Suit.DIAMONDS);

export const TWO_OF_CLUBS = new Card(Rank.TWO, Suit.CLUBS);
export const EIGHT_OF_CLUBS = new Card(Rank.EIGHT, Suit.CLUBS);
export const ACE_OF_CLUBS = new Card(Rank.ACE, Suit.CLUBS);

export const OTHER_THREE_OF_SPADES = new Card(Rank.THREE, Suit.SPADES);
export const OTHER_TWO_OF_HEARTS = new Card(Rank.TWO, Suit.HEARTS);
export const OTHER_ACE_OF_HEARTS = new Card(Rank.ACE, Suit.HEARTS);


export const ACE_HIGH_HAND = new Hand([JACK_OF_HEARTS, TWO_OF_SPADES, ACE_OF_DIAMONDS, EIGHT_OF_CLUBS, THREE_OF_SPADES]);
export const SEVEN_HIGH_HAND = new Hand([TWO_OF_DIAMONDS, THREE_OF_HEARTS, FIVE_OF_HEARTS, SIX_OF_HEARTS, SEVEN_OF_HEARTS]);
export const PAIR_OF_TWOS_HAND = new Hand([TWO_OF_HEARTS, TWO_OF_SPADES, ACE_OF_DIAMONDS, EIGHT_OF_CLUBS, THREE_OF_SPADES]);
export const PAIR_OF_EIGHTS_HAND = new Hand([JACK_OF_HEARTS, TWO_OF_SPADES, EIGHT_OF_DIAMONDS , EIGHT_OF_CLUBS, THREE_OF_SPADES]);
export const TWO_PAIR_TWOS_AND_EIGHTS_HAND = new Hand([THREE_OF_SPADES, TWO_OF_HEARTS, TWO_OF_SPADES, EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS]);
export const TWO_PAIR_TWOS_AND_ACES = new Hand([THREE_OF_SPADES, TWO_OF_HEARTS, TWO_OF_SPADES, ACE_OF_DIAMONDS, ACE_OF_CLUBS]);
export const THREE_TWOS_HAND = new Hand([TWO_OF_DIAMONDS, TWO_OF_HEARTS, TWO_OF_SPADES, ACE_OF_CLUBS, JACK_OF_HEARTS]);
export const THREE_EIGHT_HAND = new Hand([EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS, ACE_OF_DIAMONDS, JACK_OF_HEARTS, EIGHT_OF_HEARTS]);
export const LOW_STRAIGHT_HAND = new Hand ([TWO_OF_DIAMONDS, THREE_OF_HEARTS, FOUR_OF_SPADES, FIVE_OF_HEARTS, SIX_OF_HEARTS]);
export const HIGH_STRAIGHT_HAND = new Hand([ACE_OF_CLUBS, KING_OF_HEARTS, QUEEN_OF_HEARTS, JACK_OF_HEARTS, TEN_OF_HEARTS]);
export const LOW_FLUSH_HAND = new Hand([TWO_OF_HEARTS, THREE_OF_HEARTS, EIGHT_OF_HEARTS, NINE_OF_HEARTS, FIVE_OF_HEARTS]);
export const HIGH_FLUSH_HAND = new Hand([ACE_OF_HEARTS, TWO_OF_HEARTS, KING_OF_HEARTS, SEVEN_OF_HEARTS, EIGHT_OF_HEARTS]);
export const LOW_FULL_HOUSE_HAND = new Hand([TWO_OF_DIAMONDS, TWO_OF_HEARTS, TWO_OF_SPADES, ACE_OF_CLUBS, ACE_OF_DIAMONDS]);
export const TIED_LOWER_FULL_HOUSE_HAND = new Hand([TWO_OF_DIAMONDS, TWO_OF_HEARTS, TWO_OF_SPADES, EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS]);
export const HIGH_FULL_HOUSE_HAND = new Hand([EIGHT_OF_CLUBS, EIGHT_OF_DIAMONDS, EIGHT_OF_HEARTS, TWO_OF_DIAMONDS, TWO_OF_HEARTS]);
export const FOUR_OF_A_KIND_LOW_HAND = new Hand ([TWO_OF_DIAMONDS, TWO_OF_HEARTS, TWO_OF_SPADES, TWO_OF_CLUBS, ACE_OF_HEARTS]);
export const FOUR_OF_A_KIND_HIGH_HAND = new Hand([ACE_OF_CLUBS, ACE_OF_DIAMONDS, ACE_OF_HEARTS, ACE_OF_SPADES, TWO_OF_CLUBS]);
export const STRAIGHT_FLUSH_LOW_HAND = new Hand([FOUR_OF_HEARTS, FIVE_OF_HEARTS, SIX_OF_HEARTS, SEVEN_OF_HEARTS, EIGHT_OF_HEARTS]);
export const STRAIGHT_FLUSH_HIGH_HAND = new Hand([NINE_OF_HEARTS, TEN_OF_HEARTS, JACK_OF_HEARTS, QUEEN_OF_HEARTS, KING_OF_HEARTS]);
export const ROYAL_FLUSH = new Hand([TEN_OF_HEARTS, JACK_OF_HEARTS, QUEEN_OF_HEARTS, ACE_OF_HEARTS, KING_OF_HEARTS]);
export const FIVE_OF_A_KIND_LOW = new Hand([TWO_OF_CLUBS, TWO_OF_DIAMONDS, TWO_OF_HEARTS, TWO_OF_SPADES, OTHER_TWO_OF_HEARTS]);
export const FIVE_OF_A_KIND_HIGH = new Hand([ACE_OF_CLUBS, ACE_OF_DIAMONDS, ACE_OF_HEARTS, ACE_OF_SPADES, OTHER_ACE_OF_HEARTS]);


export const SIX_CARDS = new Hand ([TEN_OF_HEARTS, TWO_OF_CLUBS, ACE_OF_CLUBS, JACK_OF_HEARTS, QUEEN_OF_HEARTS, EIGHT_OF_DIAMONDS]);
